# Hyperparameter ablation: Triplet margin = 0.1
# Test impact of smaller margin on triplet loss

model:
  name: 'resnet50_fc512'

data:
  type: 'image'
  root: 'datasets'
  height: 256
  width: 128
  workers: 8
  sources: ['soccernetv3']
  targets: ['soccernetv3', 'soccernetv3_test', 'soccernetv3_challenge']

soccernetv3:
  training_subset: 0.01

sampler:
  train_sampler: RandomIdentitySampler
  train_sampler_t: RandomIdentitySampler
  num_instances: 4

loss:
  name: 'triplet'
  softmax:
    label_smooth: True
  triplet:
    margin: 0.1  # Smaller margin
    weight_t: 0.5
    weight_x: 0.5

train:
  batch_size: 128
  print_freq: 10
  max_epoch: 60
  lr: 0.0003
  weight_decay: 5e-4

test:
  ranks: [1, 5, 10, 20]
  export_ranking_results: True
  eval_freq: 10